### ISSUE TITLE
500 error when in development mode

### ISSUE THREAD

**Issue by taujin** [kadetXx/nuxt-gsap-starter#1]
I'm new to nuxt so I'm completely clueless on why the repository runs without problem when built for production. Maybe someone can give some insight?

### Reproduction
1. Clone repository
2. Install packages
3. npm/yarn/pnpm run dev

### Bug
```
500 Cannot set properties of undefined (setting 'hello')

at Interactions.onPreloaded (http://127.0.0.1:3000/_nuxt/interactions/index.ts:28:27)
at Interactions.createPreloader (http://127.0.0.1:3000/_nuxt/interactions/index.ts:25:10)
at new Interactions (http://127.0.0.1:3000/_nuxt/interactions/index.ts:11:10)
at http://127.0.0.1:3000/_nuxt/app.js:10:7
at http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:4077:88
at callWithErrorHandling (http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:1567:18)
at callWithAsyncErrorHandling (http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:1575:17)
at hook.__weh.hook.__weh (http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:4057:19)
at flushPostFlushCbs (http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:1733:41)
at hydrate2 (http://127.0.0.1:3000/_nuxt/node_modules/.cache/vite/client/deps/vue.js?v=64f9b94b:5923:5)```

**Comment by kadetXx** [comment]
Hi @taujin, thanks for reporting this issue, it has now been resolved by this PR #2
